#!/bin/bash -eu

# 1行分を出力
# Usage: typing_row {sentence} [{wait time}]
function typing_row()
{
    for s in `echo ${1} | fold -s1`
    do
        echo -n ${s}

        # 指定した時間待機
        if [ ${#} -lt 2 ]
        then
            sleep 0.05
        else
            sleep ${2}
        fi
    done

    echo
}

#環境変数の変更を局所化するため、()で囲む
(
    #改行文字のみを区切り文字とする
    IFS=$'\n'

    if [ ${#} -eq 0 ] || [ 2 -lt ${#} ]
    then
        typing_row "<Usage>"
        typing_row " [Input from file]"
        typing_row "  $ typing {file path} [{wait time (default: 0.05)}]"
        typing_row " [Input from stdin]"
        typing_row "  $ typing - [{wait time (default: 0.05)}]"
        exit 1
    fi

    for r in `cat ${1}`
    do
        typing_row ${r} ${2}
    done
)
